# Generated by Django 4.2.2 on 2023-06-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
